package aplicacion.modelo.dominio;
// Generated 26-jun-2019 23:30:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrito generated by hbm2java
 */
public class Carrito  implements java.io.Serializable {


     private Integer carCodigo;
     private Usuario usuario;
     private double carTotal;
     private Set helCars = new HashSet(0);

    public Carrito() {
    }

    public Carrito(Usuario usuario, double carTotal) {
        this.usuario = usuario;
        this.carTotal = carTotal;
    }

    public Carrito(Integer carCodigo, Usuario usuario) {
        this.carCodigo = carCodigo;
        this.usuario = usuario;
    }

    
    public Carrito(Integer carCodigo, Usuario usuario, double carTotal,Set helCars) {
        this.carCodigo = carCodigo;
        this.usuario = usuario;
        this.carTotal = carTotal;
        this.helCars = helCars;
    }
    
    

    public Integer getCarCodigo() {
        return this.carCodigo;
    }
    
    public void setCarCodigo(Integer carCodigo) {
        this.carCodigo = carCodigo;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    public double getCarTotal() {
        return this.carTotal;
    }
    
    public void setCarTotal(double carTotal) {
        this.carTotal = carTotal;
    }
    public Set getHelCars() {
        return this.helCars;
    }
    
    public void setHelCars(Set helCars) {
        this.helCars = helCars;
    }




}

