package aplicacion.modelo.dominio;
// Generated 21-jun-2019 18:35:47 by Hibernate Tools 4.3.1



/**
 * ComHelId generated by hbm2java
 */
public class ComHelId  implements java.io.Serializable {


     private int comCodigoCompra;
     private int helCodigoHelado;

    public ComHelId() {
    }

    public ComHelId(int comCodigoCompra, int helCodigoHelado) {
       this.comCodigoCompra = comCodigoCompra;
       this.helCodigoHelado = helCodigoHelado;
    }
   
    
    public int getComCodigoCompra() {
        return this.comCodigoCompra;
    }
    
    public void setComCodigoCompra(int comCodigoCompra) {
        this.comCodigoCompra = comCodigoCompra;
    }
    public int getHelCodigoHelado() {
        return this.helCodigoHelado;
    }
    
    public void setHelCodigoHelado(int helCodigoHelado) {
        this.helCodigoHelado = helCodigoHelado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComHelId) ) return false;
		 ComHelId castOther = ( ComHelId ) other; 
         
		 return (this.getComCodigoCompra()==castOther.getComCodigoCompra())
 && (this.getHelCodigoHelado()==castOther.getHelCodigoHelado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getComCodigoCompra();
         result = 37 * result + this.getHelCodigoHelado();
         return result;
   }   


}


