package aplicacion.modelo.dominio;
// Generated 21-jun-2019 18:35:47 by Hibernate Tools 4.3.1



/**
 * ComHel generated by hbm2java
 */
public class ComHel  implements java.io.Serializable {


     private ComHelId id;
     private Compra compras;
     private Helado helados;
     private int cantHelado;

    public ComHel() {
    }

    public ComHel(ComHelId id, Compra compras, Helado helados, int cantHelado) {
       this.id = id;
       this.compras = compras;
       this.helados = helados;
       this.cantHelado = cantHelado;
    }
   
    
    public ComHelId getId() {
        return this.id;
    }
    
    public void setId(ComHelId id) {
        this.id = id;
    }

    public Compra getCompras() {
        return compras;
    }

    public void setCompras(Compra compras) {
        this.compras = compras;
    }

    public Helado getHelados() {
        return helados;
    }

    public void setHelados(Helado helados) {
        this.helados = helados;
    }
    
    public int getCantHelado() {
        return this.cantHelado;
    }
    
    public void setCantHelado(int cantHelado) {
        this.cantHelado = cantHelado;
    }




}


