package aplicacion.modelo.dominio;
// Generated 26-jun-2019 23:12:26 by Hibernate Tools 4.3.1



/**
 * HelCar generated by hbm2java
 */
public class HelCar  implements java.io.Serializable {


     private HelCarId id;
     private Carrito carrito;
     private Helado helado;
     private Integer cantHelado;

    public HelCar() {
    }

    public HelCar(HelCarId id, Carrito carrito, Helado helado, int cantHelado) {
        this.id = id;
        this.carrito = carrito;
        this.helado = helado;
        this.cantHelado = cantHelado;
    }

    
   
    public HelCarId getId() {
        return this.id;
    }
    
    public void setId(HelCarId id) {
        this.id = id;
    }
    public Carrito getCarrito() {
        return this.carrito;
    }
    
    public void setCarrito(Carrito carrito) {
        this.carrito = carrito;
    }

    public Helado getHelado() {
        return helado;
    }

    public void setHelado(Helado helado) {
        this.helado = helado;
    }
    
    public Integer getCantHelado() {
        return this.cantHelado;
    }
    
    public void setCantHelado(Integer cantHelado) {
        this.cantHelado = cantHelado;
    }




}


