package aplicacion.modelo.dominio;
// Generated 26-jun-2019 23:12:26 by Hibernate Tools 4.3.1



/**
 * HelCarId generated by hbm2java
 */
public class HelCarId  implements java.io.Serializable {


     private int carritoCarCodigo;
     private int heladosHelCodigoHelado;

    public HelCarId() {
    }

    public HelCarId(int carritoCarCodigo, int heladosHelCodigoHelado) {
       this.carritoCarCodigo = carritoCarCodigo;
       this.heladosHelCodigoHelado = heladosHelCodigoHelado;
    }
   
    public int getCarritoCarCodigo() {
        return this.carritoCarCodigo;
    }
    
    public void setCarritoCarCodigo(int carritoCarCodigo) {
        this.carritoCarCodigo = carritoCarCodigo;
    }
    public int getHeladosHelCodigoHelado() {
        return this.heladosHelCodigoHelado;
    }
    
    public void setHeladosHelCodigoHelado(int heladosHelCodigoHelado) {
        this.heladosHelCodigoHelado = heladosHelCodigoHelado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HelCarId) ) return false;
		 HelCarId castOther = ( HelCarId ) other; 
         
		 return (this.getCarritoCarCodigo()==castOther.getCarritoCarCodigo())
 && (this.getHeladosHelCodigoHelado()==castOther.getHeladosHelCodigoHelado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCarritoCarCodigo();
         result = 37 * result + this.getHeladosHelCodigoHelado();
         return result;
   }   


}


