package aplicacion.modelo.dominio;
// Generated 21-jun-2019 18:35:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {
/**
     * codigo unico que representa a cada oferta
     */
    private Integer codigoOferta;
    /**
     * Helados que pueden inclurse en la oferta
     */
    private Set<Helado> heladosOferta;
    /**
     * tipo de oferta que se aplicara
     */
    private String tipoOferta;
    /**
     * fecha inicio de la oferta
     */
    private Date fechaInicio;
    /**
     * fecha final de la oferta
     */
    private Date fechaFinal;
    /**
     * estado de la oferta
     */
    private boolean estado;
    /**
     * Constructor por defecto
     */
    public Oferta() {
        this.estado = true;
    }
    /**
     * Constructor parametrizado
     * @param codigoOferta codigo unico que representa a cada oferta
     * @param heladosOferta Helados que pueden inclurse en la oferta
     * @param tipoOferta Helados que pueden inclurse en la oferta
     * @param fechaInicio fecha inicio de la oferta
     * @param fechaFinal fecha final de la oferta
     */
    public Oferta(Integer codigoOferta, Set<Helado> heladosOferta, String tipoOferta, Date fechaInicio, Date fechaFinal, boolean estado) {    
        this.codigoOferta = codigoOferta;
        this.heladosOferta = heladosOferta;
        this.tipoOferta = tipoOferta;
        this.fechaInicio = fechaInicio;
        this.fechaFinal = fechaFinal;
        this.estado = estado;
    }

    /**
     * @return the codigoOferta
     */
    public Integer getCodigoOferta() {
        return codigoOferta;
    }

    /**
     * @param codigoOferta the codigoOferta to set
     */
    public void setCodigoOferta(Integer codigoOferta) {
        this.codigoOferta = codigoOferta;
    }

    /**
     * @return the heladosOferta
     */
    public Set<Helado> getHeladosOferta() {
        return heladosOferta;
    }

    /**
     * @param heladosOferta the heladosOferta to set
     */
    public void setHeladosOferta(Set<Helado> heladosOferta) {
        this.heladosOferta = heladosOferta;
    }

    /**
     * @return the tipoOferta
     */
    public String getTipoOferta() {
        return tipoOferta;
    }

    /**
     * @param tipoOferta the tipoOferta to set
     */
    public void setTipoOferta(String tipoOferta) {
        this.tipoOferta = tipoOferta;
    }

    /**
     * @return the fechaInicio
     */
    public Date getFechaInicio() {
        return fechaInicio;
    }

    /**
     * @param fechaInicio the fechaInicio to set
     */
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    /**
     * @return the fechaFinal
     */
    public Date getFechaFinal() {
        return fechaFinal;
    }

    /**
     * @param fechaFinal the fechaFinal to set
     */
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    @Override
    public String toString() {
        return "Oferta{" + "codigoOferta=" + codigoOferta + ", heladosOferta=" + heladosOferta + ", tipoOferta=" + tipoOferta + ", fechaInicio=" + fechaInicio + ", fechaFinal=" + fechaFinal + ", estado=" + estado + '}';
    }

}


