package aplicacion.modelo.dominio;
// Generated 21-jun-2019 18:35:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private Integer codigoOferta;
     private Set heladosOferta = new HashSet(0);
     private double descuento;

    public Oferta() {
    }

	
    public Oferta(double descuento) {
        this.descuento = descuento;
    }
    public Oferta(Set heladosOferta, double descuento) {
       this.heladosOferta = heladosOferta;
       this.descuento = descuento;
    }
   
    public Integer getCodigoOferta() {
        return this.codigoOferta;
    }
    
    public void setCodigoOferta(Integer codigoOferta) {
        this.codigoOferta = codigoOferta;
    }
    public Set getHeladosOferta() {
        return this.heladosOferta;
    }
    
    public void setHeladosOferta(Set heladosOferta) {
        this.heladosOferta = heladosOferta;
    }
    public double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(double descuento) {
        this.descuento = descuento;
    }




}


